config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights, only: %i[index] do
    get 'search', on: :collection
  end

  resources :bookings, only: %i[new create show]

  # Defines the root path route ("/")
  root 'flights#index'
end

app/models/airport.rb
# frozen_string_literal: true

# Airport model
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id', inverse_of: 'departure_airport'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id', inverse_of: 'arrival_airport'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

# Booking model
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
# frozen_string_literal: true

# Flight model
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', inverse_of: 'departing_flights'
  belongs_to :arrival_airport, class_name: 'Airport', inverse_of: 'arriving_flights'

  has_many :bookings

  scope :flight_dates, -> { select(:start).distinct.all.map { |date| date.start.strftime('%d/%m/%Y') }.uniq }

  def flight_name
    "#{departure_airport.code} - #{arrival_airport.code}: #{start.localtime.strftime('%d/%m/%Y %H:%M:%S')}
     (#{duration} #{'hour'.pluralize(duration)})"
  end
end

app/models/passenger.rb
# frozen_string_literal: true

# Passenger class
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

# Bookings controller and routes
class BookingsController < ApplicationController
  def new
    @selected_flight = Flight.find(params[:selected_id])
    @booking = Booking.new(passanger_count: params[:passengers])
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create # rubocop:disable Metrics/MethodLength
    selected_flight = Flight.find(params[:flight_id])
    @booking = selected_flight.bookings.build(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger, flight: selected_flight)
                       .booking_confirmation.deliver_later
      end

      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:passanger_count, passengers_attributes: %i[id name email])
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

# Flight controller for routes
class FlightsController < ApplicationController
  before_action :set_parameters, only: %i[index search]

  def index; end

  def search
    flight_date = Time.parse(params[:flight_date])

    @available_flights = Flight.where(departure_airport_id: params[:departure_airport_id])
                               .where(arrival_airport_id: params[:arrive_airport_id])
                               .where(start: flight_date.midnight..flight_date.change({ hour: 23, min: 59, sec: 59 }))

    render :index
  end

  private

  def set_parameters
    @flights = Flight.all
    @airports = Airport.all
    @flight_dates = Flight.flight_dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="index-container">
    <div class="flight-container">
        <p class="title">Booking Information</p>
        <%= form_with model: @booking do |f| %>
            <%= label_tag :flight_id, @selected_flight.flight_name %>
            <%= hidden_field_tag :flight_id, @selected_flight.id %>
            <div class="field">
                <%= f.label :passanger_count, 'Passengers' %>
                <%= f.text_field :passanger_count, readonly: true %>
            </div>
            <p class="title">Passenger Info</p>
            <%= f.fields_for :passengers do |p_f| %>
                <div class="field">
                    <%= p_f.label :name %>
                    <%= p_f.text_field :name %>
                </div>
                <div class="field">
                    <%= p_f.label :email %>
                    <%= p_f.email_field :email %>
                </div>
            <% end %>
            <div class="actions">
                <%= f.submit 'Submit Booking', class: 'submit-button' %>
            </div>
        <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="index-container">
    <div class="flight-container">
        <p class="title">Booking</p>
        <div class="info-field">
            <p class="subtitle"> Flight </p>
            <p class="normal"> <%= @booking.flight.flight_name %> </p>
        </div>
        <p class="subtitle">Passengers</p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                </tr>  
            </thead>
            <tbody>
                <% @booking.passengers.each do |passenger| %>
                    <tr>
                        <td> <%= passenger.name %> </td>
                        <td> <%= passenger.email %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <div class="actions">
            <%= link_to 'Home', root_path %>
        </div>
    </div>
</div>

app/views/flights/index.html.erb
<div class="index-container">
    <div class="flight-container">
        <p class="title">Flight Scheduler</p>
        <%= form_with url: search_flights_path, method: :get do |f| %>
            <div class="double-drop-field">
                <%= f.label :departure_airport_id %>
                <%= f.label :arrive_airport_id %>
                <%= f.collection_select :departure_airport_id, @airports, :id, :code %>
                <%= f.collection_select :arrive_airport_id, @airports, :id, :code %>
            </div>
            <div class="drop-field">
                <%= f.label :passengers %>
                <%= f.select :passengers, [1, 2, 3, 4] %>
            </div>
            <div class="drop-field">
                <%= f.label :flight_date %>
                <%= f.select :flight_date, @flight_dates %>
            </div>
            <div class="actions">
                <%= f.submit 'Search flights', class: 'submit-button' %>
            </div>
        <% end %>
    </div>
    <% unless @available_flights.nil? %>
        <div class="available-container"> 
            <% if @available_flights.empty? %>
                <p class="message">No flights found.</p>
            <% else %>
                <div class="available">
                    <p class="title">Available Flights</p>
                    <%= form_with url: new_booking_path, method: :get do |f| %>
                        <div class="radio-field">
                            <%= f.collection_radio_buttons :selected_id, @available_flights, :id, :flight_name, include_hidden: false %>
                        </div>
                        <%= f.hidden_field :passengers, value: params[:passengers] %>
                        <div class="actions">
                            <%= f.submit 'Book Flight', class: 'submit-button' %>
                        </div>
                    <% end %>
                </div>
                
            <% end %>     
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>